before:
  hooks:
    - go mod download

builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/vs4vijay/vizix/pkg/version.SemVer={{.Version}} -X=github.com/vs4vijay/vizix/pkg/version.GitCommit={{.Commit}} -X github.com/vs4vijay/vizix/pkg/version.BuildTime={{.Date}}

brews:
  - name: vizix
    goarm: 6
    github:
      owner: vs4vijay
      name: homebrew-vizix
    url_template: "https://github.com/vs4vijay/vizix/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: vs4vijay
      email: vs4vijay@gmail.com
    folder: Formula
    description: "vizix - Software to create fun and profit"
    skip_upload: false
    install: |
      bin.install "vizix"
    test: |
      system "#{bin}/vizix --version"

archives:
- replacements:
    darwin: mac
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
