name: PR Gate

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.31.0
          args: --issues-exit-code=0

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Run tests
        run: go test ./...
