name: PR Gate

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31.0
          args: --issues-exit-code=0

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Run tests
        run: go test ./...

  check-merge-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for merge conflicts
        uses: mschilde/auto-label-merge-conflicts@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          label-name: 'merge-conflict'
